### PR TITLE
Darshan udfs

### PR DESCRIPTION
**Pull request by darshanv6**

### CODE REVIEW

**Comment by shubhamInfoWorks** [comment]
@darshanv6 Change return type, from Object To specific

**Comment by darshanv6** [comment]
> @darshanv6 Change return type, from Object To specific

@shubhamInfoWorks done. Have changed return types accordingly in other files as well

**Comment by shubhamInfoWorks** [comment]
@darshanv6 getTime won't return string, can u check again?

**Comment by darshanv6** [comment]
> @darshanv6 getTime won't return string, can u check again?

@shubhamInfoWorks .format converts it to a String of the given format.

**Pull request merged**
